apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-tilbake
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8030
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvfamilie-tilbake
        mountPath: /var/run/secrets/nais.io/srvfamilie-tilbake
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ba-sak
          namespace: default
        - application: familie-ef-sak
          namespace: default
        - application: familie-ks-sak
          namespace: default
        - application: familie-tilbake-frontend
          namespace: teamfamilie
          cluster: prod-gcp
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: "1"
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-tilbake.nais.adeo.no
    - https://familie-tilbake.intern.nav.no
    - https://familie-tilbake.prod-fss-pub.nais.io
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: CREDENTIAL_USERNAME
      value: /run/secrets/nais.io/srvfamilie-tilbake/username
    - name: CREDENTIAL_PASSWORD
      value: /run/secrets/nais.io/srvfamilie-tilbake/password
