package no.nav.tilbakekreving.kontrakter.frontend.models

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 *
 * @param svarAlternativer
 * @param type
 * @param forhåndsvarselinfo
 * @param brukeruttalelse
 * @param uttalelsesfrist
 * @param begrunnelseForUnntak
 * @param unntakDetaljer
 */
@JsonIgnoreProperties(
    value = ["type"], // ignore manually set type, it will be automatically generated by Jackson during serialization
    allowSetters = true, // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = IkkeVurdertDto::class, name = "ikke_vurdert"),
    JsonSubTypes.Type(value = ForhaandsvarselErSendtDto::class, name = "sendt"),
    JsonSubTypes.Type(value = ForhaandsvarselUnntakDto::class, name = "unntak"),
)
sealed interface ForhaandsvarselstegDto

object IkkeVurdertDto : ForhaandsvarselstegDto
