package no.nav.tilbakekreving.kontrakter.frontend.models

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

@JsonIgnoreProperties(
    value = ["forståelse"], // ignore manually set forståelse, it will be automatically generated by Jackson during serialization
    allowSetters = true, // allows the forståelse to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "forståelse", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = BurdeForstaattDto::class, name = "burdeForstått"),
    JsonSubTypes.Type(value = ForstoDto::class, name = "forsto"),
)
sealed interface ForstaaelseDto
