package no.nav.tilbakekreving.kontrakter.frontend.models

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 *
 * @param tekst
 * @param tittel
 * @param underavsnitt
 */
@JsonIgnoreProperties(
    value = ["type"], // ignore manually set type, it will be automatically generated by Jackson during serialization
    allowSetters = true, // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = RentekstElementDto::class, name = "rentekst"),
    JsonSubTypes.Type(value = UnderavsnittElementDto::class, name = "underavsnitt"),
)
interface RotElementDto
