application:
  name: familie-tilbake

server:
  port: 8030
  servlet:
    context-path: /

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main.banner-mode: "off"
  data:
    jdbc:
      repositories:
        enabled: true
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true
  datasource:
    hikari:
      maximum-pool-size: 2
      connection-test-query: "select 1"
      max-lifetime: 30000
      minimum-idle: 1
      data-source-properties.stringtype: unspecified # Nødvendig for å kunde sende en String til et json-felt i PostgresSql
  aop:
    auto: true
    proxy-target-class: true

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: ${AZUREAD_DISCOVERY_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}
    cookie_name: azure_token
  client:
    registration:
      familie-integrasjoner:
        resource-url: ${FAMILIE_INTEGRASJONER_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${FAMILIE_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-integrasjoner-clientcredentials:
        resource-url: ${FAMILIE_INTEGRASJONER_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${FAMILIE_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "status/isAlive"
  metrics.export.prometheus.enabled: true
  health:
    db:
      enabled: true

oppdrag.mq:
  queuemanager: QM1
  kravgrunnlag: DEV.QUEUE.1
  channel: DEV.ADMIN.SVRCONN
  hostname: localhost
  port: 1414
  user: admin
  password: passw0rd
  enabled: true

rolle:
  barnetrygd:
    veileder: ""
    saksbehandler: ""
    beslutter: ""
  enslig:
    veileder: ""
    saksbehandler: ""
    beslutter: ""
  kontantstøtte:
    veileder: ""
    saksbehandler: ""
    beslutter: ""

AZUREAD_DISCOVERY_URL: https://login.microsoftonline.com/navno.onmicrosoft.com/v2.0/.well-known/openid-configuration
AZUREAD_TOKEN_ENDPOINT_URL: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/v2.0/token
BA_SAK_CLIENT_ID: ""
EF_SAK_CLIENT_ID: ""
SECURITYTOKENSERVICE_URL: https://sts-q1.preprod.local/SecurityTokenServiceProvider/ # brukes kun av integrasjonstester
PDL_URL: https://pdl-api-q1.dev-fss-pub.nais.io
FAMILIE_TILBAKE_FRONTEND_CLIENT_ID: "dummy"
FORELDELSE_ANTALL_MÅNED: 30
TILBAKEKREVING_V1_URL: https://cics-q1.adeo.no/oppdrag/K231CW80
ACCEPTED_CLIENTS: ${BA_SAK_CLIENT_ID}, ${EF_SAK_CLIENT_ID}, ${FAMILIE_TILBAKE_FRONTEND_CLIENT_ID}
PROXY_URL: http://webproxy-nais.nav.no:8088
CRON_HÅNDTER_GAMMEL_KRAVGRUNNLAG: 0 0 7 ? * MON-FRI
