
spring:
  datasource:
    url: jdbc:postgresql://b27dbvl023.preprod.local:5432/familie-tilbake

no.nav.security.jwt.issuer.azuread.proxyurl: http://webproxy-nais.nav.no:8088

oppdrag.mq:
  queuemanager: MQLS02
  kravgrunnlag: QA.Q1_FAMILIE_TILBAKE.KRAVGRUNNLAG
  channel: Q1_FAMILIE_TILBAKE
  hostname: b27apvl220.preprod.local
  port: 1413
  user: ${SERVICEUSER_USERNAME}
  password: ${SERVICEUSER_PASSWORD}
  enabled: true

rolle:
  barnetrygd:
    veileder: "93a26831-9866-4410-927b-74ff51a9107c"
    saksbehandler: "d21e00a4-969d-4b28-8782-dc818abfae65"
    beslutter: "9449c153-5a1e-44a7-84c6-7cc7a8867233"
  enslig:
    veileder: "19dcbfde-4cdb-4c64-a1ea-ac9802b03339"
    saksbehandler: "ee5e0b5e-454c-4612-b931-1fe363df7c2c"
    beslutter: "01166863-22f1-4e16-9785-d7a05a22df74"
  kontantstøtte:
    veileder: ""
    saksbehandler: ""
    beslutter: ""



FAMILIE_INTEGRASJONER_URL: http://familie-integrasjoner-q1.teamfamilie
SECURITYTOKENSERVICE_URL: https://sts-q1.preprod.local/SecurityTokenServiceProvider/

AZUREAD_DISCOVERY_URL: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
AZUREAD_TOKEN_ENDPOINT_URL: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
PDL_URL: http://pdl-api-q1.pdl
FORELDELSE_ANTALL_MÅNED: 3
OPPRETTELSE_DAGER_BEGRENSNING: 1
TILBAKEKREVING_V1_URL: https://cics-q1.adeo.no/oppdrag/K231CW80
