no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: http://mock-oauth2-server:1111/v2.0/.well-known/openid-configuration
    accepted_audience: api://${TILBAKE_CLIENT_ID}/.default
    proxyurl:
    cookie_name: azure_token
  client:
    registration:
      familie-integrasjoner:
        resource-url: ${FAMILIE_INTEGRASJONER_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${FAMILIE_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${TILBAKE_CLIENT_ID}
          client-secret: ${TILBAKE_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-integrasjoner-clientcredentials:
        resource-url: ${FAMILIE_INTEGRASJONER_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${FAMILIE_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${TILBAKE_CLIENT_ID}
          client-secret: ${TILBAKE_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-historikk:
        resource-url: ${FAMILIE_HISTORIKK_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${FAMILIE_HISTORIKK_SCOPE}
        authentication:
          client-id: ${TILBAKE_CLIENT_ID}
          client-secret: ${TILBAKE_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-historikk-clientcredentials:
        resource-url: ${FAMILIE_HISTORIKK_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${FAMILIE_HISTORIKK_SCOPE}
        authentication:
          client-id: ${TILBAKE_CLIENT_ID}
          client-secret: ${TILBAKE_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      pdl:
        resource-url: ${PDL_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${PDL_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      pdl-clientcredentials:
        resource-url: ${PDL_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${PDL_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-oppdrag:
        resource-url: ${FAMILIE_OPPDRAG_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${FAMILIE_OPPDRAG_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-oppdrag-clientcredentials:
        resource-url: ${FAMILIE_OPPDRAG_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: ${FAMILIE_OPPDRAG_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

logging:
  config: "classpath:logback-e2e.xml"

spring:
  datasource:
    url: jdbc:postgresql://postgres-tilbake:5432/familie-tilbake
    username: familie
    password: familie-pwd
  cloud:
    vault:
      database:
        role: familie

ACCEPTED_CLIENTS: ${BA_SAK_CLIENT_ID}, ${EF_SAK_CLIENT_ID}, ${FAMILIE_TILBAKE_FRONTEND_CLIENT_ID}
STS_URL: http://nav-auth-mock:8200/nais-sts/token
PDL_URL: http://familie-mock-server:1337/rest/api/pdl/
PDL_SCOPE: api://dummy/.default
SECURITYTOKENSERVICE_URL: https://localhost:8063/soap/SecurityTokenServiceProvider/

FAMILIE_INTEGRASJONER_URL: http://familie-integrasjoner:8085
FAMILIE_OPPDRAG_URL: #Mockes ut lokalt
AZUREAD_TOKEN_ENDPOINT_URL: http://mock-oauth2-server:1111/v2.0/token
FAMILIE_HISTORIKK_URL: http://familie-historikk:8050/api

CREDENTIAL_USERNAME: srvfamilie-tilbake
CREDENTIAL_PASSWORD:

prosessering:
  fixedDelayString:
    in:
      milliseconds: 2500
