no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${AZURE_APP_CLIENT_ID}
    proxyurl: http://webproxy-nais.nav.no:8088
    cookie_name: azure_token

ACCEPTED_CLIENTS: ${BA_SAK_CLIENT_ID}, ${EF_SAK_CLIENT_ID}, ${FAMILIE_TILBAKE_FRONTEND_CLIENT_ID}

spring:
  datasource:
    url: jdbc:postgresql://b27dbvl023.preprod.local:5432/familie-tilbake

SECURITYTOKENSERVICE_URL: https://sts-q1.preprod.local/SecurityTokenServiceProvider/

AZUREAD_DISCOVERY_URL: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
AZUREAD_TOKEN_ENDPOINT_URL: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token

ENVIRONMENT_NAME: q2
rolle:
  barnetrygd:
    veileder: "93a26831-9866-4410-927b-74ff51a9107c"
    saksbehandler: "d21e00a4-969d-4b28-8782-dc818abfae65"
    beslutter: "9449c153-5a1e-44a7-84c6-7cc7a8867233"
  enslig:
    veileder: "19dcbfde-4cdb-4c64-a1ea-ac9802b03339"
    saksbehandler: "ee5e0b5e-454c-4612-b931-1fe363df7c2c"
    beslutter: "01166863-22f1-4e16-9785-d7a05a22df74"
  kontantstøtte:
    veileder: ""
    saksbehandler: ""
    beslutter: ""


