apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-tilbakekreving-tilleggsstønad
  namespace: tilbake
  labels:
    team: tilbake
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: -1
  acl:
    - team: tilbake
      application: tilbakekreving-backend
      access: readwrite
    - team: tilleggsstonader
      application: tilleggsstonader-sak
      access: readwrite
