apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-tilbake
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8030
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: false
  gcp: # Database
    sqlInstances:
      - type: POSTGRES_13
        name: familie-tilbake
        autoBackupTime: "03:00"
        databases:
          - name: familie-tilbake
            envVarPrefix: DB
  azure:
    application:
      claims:
        extra:
          - "NAVident"
        groups:
          - id: d21e00a4-969d-4b28-8782-dc818abfae65 # 0000-GA-Barnetrygd
          - id: 9449c153-5a1e-44a7-84c6-7cc7a8867233 # 0000-GA-Barnetrygd-Beslutter
          - id: 93a26831-9866-4410-927b-74ff51a9107c # 0000-GA-Barnetrygd-Veileder
          - id: ee5e0b5e-454c-4612-b931-1fe363df7c2c # 0000-GA-Enslig-Forsorger-Saksbehandler
          - id: 01166863-22f1-4e16-9785-d7a05a22df74 # 0000-GA-Enslig-Forsorger-Beslutter
          - id: 19dcbfde-4cdb-4c64-a1ea-ac9802b03339 # 0000-GA-Enslig-Forsorger-Veileder
          - id: 928636f4-fd0d-4149-978e-a6fb68bb19de # 0000-GA-STDAPPS - tilgang til prosessering
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: familie-ba-sak
          namespace: teamfamilie
          cluster: dev-fss
        - application: familie-ef-sak
          namespace: teamfamilie
        - application: familie-ks-sak
          namespace: default
        - application: familie-tilbake-frontend
          namespace: teamfamilie
          cluster: dev-gcp
        - application: ida
          namespace: default
          cluster: prod-fss
        - application: familie-prosessering
          namespace: teamfamilie
          cluster: dev-gcp
    outbound:
      rules:
        - application: familie-historikk
      external:
        - host: unleash.nais.io
        - host: familie-integrasjoner-q1.dev-fss-pub.nais.io
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: "1"
    requests:
      memory: 512Mi
      cpu: 500m
  ingresses:
    - https://familie-tilbake.dev.intern.nav.no
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod-gcp
  kafka:
    pool: nav-dev