---
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: familie-tilbake-lokal
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  claims:
    extra:
      - "NAVident"
    groups:
      - id: d21e00a4-969d-4b28-8782-dc818abfae65 # 0000-GA-Barnetrygd
      - id: 9449c153-5a1e-44a7-84c6-7cc7a8867233 # 0000-GA-Barnetrygd-Beslutter
      - id: 93a26831-9866-4410-927b-74ff51a9107c # 0000-GA-Barnetrygd-Veileder
      - id: ee5e0b5e-454c-4612-b931-1fe363df7c2c # 0000-GA-Enslig-Forsorger-Saksbehandler
      - id: 01166863-22f1-4e16-9785-d7a05a22df74 # 0000-GA-Enslig-Forsorger-Beslutter
      - id: 19dcbfde-4cdb-4c64-a1ea-ac9802b03339 # 0000-GA-Enslig-Forsorger-Veileder
      - id: c62e908a-cf20-4ad0-b7b3-3ff6ca4bf38b # teamfamilie-forvaltning
      - id: 928636f4-fd0d-4149-978e-a6fb68bb19de # 0000-GA-STDAPPS - tilgang til prosessering
  preAuthorizedApplications:
    - application: familie-tilbake-frontend-lokal
      cluster: dev-gcp
      namespace: teamfamilie
    - application: familie-ba-sak
      cluster: dev-gcp
    - application: familie-ks-sak
      cluster: dev-gcp
    - application: familie-ba-sak-lokal
      cluster: dev-gcp
      namespace: teamfamilie
    - application: familie-ef-sak-lokal
      cluster: dev-gcp
      namespace: teamfamilie
    - application: familie-ks-sak-lokal
      cluster: dev-gcp
      namespace: teamfamilie
    - application: familie-ef-iverksett-lokal
      cluster: dev-gcp
      namespace: teamfamilie
    - application: ida
      cluster: prod-fss
      namespace: traktor
  replyUrls:
    - url: "http://localhost:8030/swagger-ui/oauth2-redirect.html"
  tenant: trygdeetaten.no
  secretName: azuread-familie-tilbake-lokal
  singlePageApplication: true

# secret kan hentes fra cluster med "kubectl -n teamfamilie get secret azuread-familie-tilbake-lokal -o json | jq '.data | map_values(@base64d)'"
