---
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: familie-tilbake-lokal
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  claims:
    extra:
      - "NAVident"
    groups:
      - id: d21e00a4-969d-4b28-8782-dc818abfae65 # 0000-GA-Barnetrygd
      - id: 9449c153-5a1e-44a7-84c6-7cc7a8867233 # 0000-GA-Barnetrygd-Beslutter
      - id: 93a26831-9866-4410-927b-74ff51a9107c # 0000-GA-Barnetrygd-Veileder
      - id: ee5e0b5e-454c-4612-b931-1fe363df7c2c # 0000-GA-Enslig-Forsorger-Saksbehandler
      - id: 01166863-22f1-4e16-9785-d7a05a22df74 # 0000-GA-Enslig-Forsorger-Beslutter
      - id: 19dcbfde-4cdb-4c64-a1ea-ac9802b03339 # 0000-GA-Enslig-Forsorger-Veileder
      - id: 928636f4-fd0d-4149-978e-a6fb68bb19de # 0000-GA-STDAPPS - tilgang til prosessering
      - id: 0ba009c4-d148-4a51-b501-4b1cf906889d # 0000-GA-SU-UFOR-saksbehandler
      - id: d75164fa-39e6-4149-956e-8404bc9080b6 # 0000-GA-SU-UFOR-attestant
  preAuthorizedApplications:
    - application: familie-tilbake-frontend-lokal
      cluster: dev-gcp
      namespace: teamfamilie
    - application: familie-ba-sak
      cluster: dev-fss
      namespace: teamfamilie
    - application: ida
      cluster: prod-fss
      namespace: default
  logoutUrl: "https://familie-tilbake.dev.intern.nav.no"
  tenant: trygdeetaten.no
  secretName: azuread-familie-tilbake-lokal
