apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: tilbakekreving-backend
  namespace: tilbake
  labels:
    team: tilbake
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: tilbake
  secretName: tilbakekreving-backend-unleash-api-token

  # Specify which environment the API token should be created for.
  # Can be one of: development, or production.
  environment: development
