package no.nav.tilbakekreving.integrasjoner.dokarkiv.domain

enum class Dokumenttype {
    BARNETRYGD_TILBAKEKREVING_VEDTAK,
    OVERGANGSSTØNAD_TILBAKEKREVING_VEDTAK,
    BARNETILSYN_TILBAKEKREVING_VEDTAK,
    SKOLEPENGER_TILBAKEKREVING_VEDTAK,
    KONTANTSTØTTE_TILBAKEKREVING_VEDTAK,
    BARNETRYGD_TILBAKEKREVING_BREV,
    OVERGANGSSTØNAD_TILBAKEKREVING_BREV,
    BARNETILSYN_TILBAKEKREVING_BREV,
    SKOLEPENGER_TILBAKEKREVING_BREV,
    KONTANTSTØTTE_TILBAKEKREVING_BREV,
}
