package no.nav.familie.tilbake.domain

enum class Aksjonspunktsdefinisjon(val kode: Int,
                                   val navn: String,
                                   val vurderingspunktsdefinisjon: Vurderingspunktsdefinisjon,
                                   val totrinnsbehandlingDefault: Boolean,
                                   val aksjonspunktstype: Aksjonspunktstype,
                                   val fristperiode: String?,
                                   val tilbakehoppVedGjenopptakelse: Boolean,
                                   val lagUtenHistorikk: Boolean,
                                   val skjermlenketype: Skjermlenketype) {

    VARSEL_OM_TILBAKEKREVING(5001,
                             "Varsel om tilbakekreving",
                             Vurderingspunktsdefinisjon.VARSELSTEG_UT,
                             false,
                             Aksjonspunktstype.MANUELL,
                             null,
                             false,
                             false,
                             Skjermlenketype.UDEFINERT),
    VURDER_TILBAKEKREVING(5002,
                          "Vurder tilbakekreving",
                          Vurderingspunktsdefinisjon.VTILBSTEG_UT,
                          true,
                          Aksjonspunktstype.MANUELL,
                          null,
                          false,
                          false,
                          Skjermlenketype.UDEFINERT),
    VENTER_PÅ_TILBAKEMELDING_FRA_BRUKER(7001,
                                        "Venter på tilbakemelding fra bruker",
                                        Vurderingspunktsdefinisjon.VARSELSTEG_UT,
                                        false,
                                        Aksjonspunktstype.AUTO,
                                        "P4W",
                                        false,
                                        false,
                                        Skjermlenketype.UDEFINERT),
    VENTER_PÅ_TILBAKEKREVINGSGRUNNLAG_FRA_ØKONOMI(7002,
                                                  "Venter på tilbakekrevingsgrunnlag fra økonomi",
                                                  Vurderingspunktsdefinisjon.TBKGSTEG_UT,
                                                  false,
                                                  Aksjonspunktstype.AUTO,
                                                  "P4W",
                                                  false,
                                                  false,
                                                  Skjermlenketype.UDEFINERT),
    VURDER_FORELDELSE(5003,
                      "Vurder foreldelse",
                      Vurderingspunktsdefinisjon.VFORELDETSTEG_UT,
                      true,
                      Aksjonspunktstype.MANUELL,
                      null,
                      false,
                      false,
                      Skjermlenketype.UDEFINERT),
    FORESLÅ_VEDTAK(5004,
                   "Foreslå vedtak",
                   Vurderingspunktsdefinisjon.FORVEDSTEG_UT,
                   true,
                   Aksjonspunktstype.MANUELL,
                   null,
                   false,
                   false,
                   Skjermlenketype.UDEFINERT),
    INNHENT_OPPLYSNING(5000,
                       "Innhent opplysning",
                       Vurderingspunktsdefinisjon.INOPPSTEG_INN,
                       false,
                       Aksjonspunktstype.MANUELL,
                       null,
                       false,
                       true,
                       Skjermlenketype.UDEFINERT),
    AVKLART_FAKTA_FOR_FEILUTBETALING(7003,
                                     "Avklart fakta for feilutbetaling",
                                     Vurderingspunktsdefinisjon.FAKTFEILUTSTEG_UT,
                                     true,
                                     Aksjonspunktstype.MANUELL,
                                     null,
                                     false,
                                     false,
                                     Skjermlenketype.UDEFINERT),
    FATTE_VEDTAK(5005,
                 "Fatte vedtak",
                 Vurderingspunktsdefinisjon.FVEDSTEG_INN,
                 false,
                 Aksjonspunktstype.MANUELL,
                 null,
                 false,
                 false,
                 Skjermlenketype.UDEFINERT),
    AVKLAR_VERGE(5030,
                 "Avklar verge",
                 Vurderingspunktsdefinisjon.FAKTAVERGESTEG_UT,
                 false,
                 Aksjonspunktstype.MANUELL,
                 null,
                 false,
                 false,
                 Skjermlenketype.UDEFINERT),
    VURDERER_HENLEGGELSE(8001,
                         "Vurderer henleggelse p.g.a manglende kravgrunnlag",
                         Vurderingspunktsdefinisjon.TBKGSTEG_UT,
                         false,
                         Aksjonspunktstype.MANUELL,
                         null,
                         true,
                         true,
                         Skjermlenketype.UDEFINERT)
}

enum class Aksjonspunktstype(val navn: String) {
    MANUELL("Manuell"),
    AUTO("Autopunkt"),
    OVERSTYRING("Overstyring"),
    SAKSBEHANDLEROVERSTYRING("Saksbehandleroverstyring"),
    UDEFINERT("Ikke Definert");
}

enum class Skjermlenketype(val navn: String) {
    FAKTA_OM_FEILUTBETALING("Fakta om feilutbetaling"),
    TILBAKEKREVING("Tilbakekreving"),
    FORELDELSE("Foreldelse"),
    VEDTAK("Vedtak"),
    FAKTA_OM_VERGE("Fakta om verge/fullmektig"),
    UDEFINERT("Ikke Definert")
}
