package no.nav.tilbakekreving.behandling

import no.nav.tilbakekreving.behandling.Enhet.Companion.enhetNavn
import no.nav.tilbakekreving.entities.EnhetEntity

class Enhet(
    val kode: String,
    val navn: String,
) {
    fun tilEntity(): EnhetEntity {
        return EnhetEntity(kode, navn)
    }

    companion object {
        fun forKode(kode: String): Enhet {
            return Enhet(
                kode = kode,
                navn = enhetNavn[kode] ?: error("Fant ikke enhetnavn for enhet med enhetNr $kode"),
            )
        }

        private val enhetNavn = mapOf(
            "0001" to "Nav familie- og pensjonsytelser Utland",
            "0101" to "Nav Halden-Aremark",
            "0104" to "Nav Moss",
            "0105" to "Nav Sarpsborg",
            "0106" to "Nav Fredrikstad",
            "0111" to "Nav Hvaler",
            "0119" to "Nav Skiptvet Marker",
            "0124" to "Nav Indre Østfold",
            "0128" to "Nav Rakkestad",
            "0135" to "Nav Råde",
            "0137" to "Nav Våler",
            "0200" to "Nav Øst-Viken",
            "0211" to "Nav Vestby",
            "0213" to "Nav Nordre Follo",
            "0214" to "Nav Ås",
            "0215" to "Nav Frogn",
            "0216" to "Nav Nesodden",
            "0219" to "Nav Bærum",
            "0220" to "Nav Asker",
            "0221" to "Nav Aurskog-Høland",
            "0228" to "Nav Rælingen",
            "0229" to "Nav Enebakk",
            "0230" to "Nav Lørenskog",
            "0231" to "Nav Lillestrøm",
            "0233" to "Nav Nittedal",
            "0235" to "Nav Ullensaker",
            "0236" to "Nav Nes i Akershus",
            "0237" to "Nav Eidsvoll Hurdal",
            "0238" to "Nav Nannestad Gjerdrum",
            "0283" to "Nav egne ansatte Øst-Viken",
            "0287" to "Nav tiltak Øst-Viken",
            "0291" to "Nav arbeidslivssenter Øst-Viken",
            "0293" to "Nav dokumentsenter Øst-Viken",
            "0296" to "Nav arbeidsrådgivning Øst-Viken",
            "0300" to "Nav Oslo",
            "0312" to "Nav Frogner",
            "0313" to "Nav St. Hanshaugen",
            "0314" to "Nav Sagene",
            "0315" to "Nav Grünerløkka",
            "0316" to "Nav Gamle Oslo",
            "0318" to "Nav Nordstrand",
            "0319" to "Nav Søndre Nordstrand",
            "0321" to "Nav Østensjø",
            "0326" to "Nav Alna",
            "0327" to "Nav Stovner",
            "0328" to "Nav Grorud",
            "0330" to "Nav Bjerke",
            "0331" to "Nav Nordre Aker",
            "0334" to "Nav Vestre Aker",
            "0335" to "Nav Ullern",
            "0383" to "Nav egne ansatte Oslo",
            "0386" to "Nav Oslo digital oppfølging",
            "0387" to "Nav tiltak Oslo",
            "0391" to "Nav arbeidslivssenter Oslo",
            "0393" to "Nav utland og fellestjenester Oslo",
            "0396" to "Nav arbeid og helse Oslo",
            "0400" to "Nav Innlandet",
            "0402" to "Nav Kongsvinger",
            "0403" to "Nav Hamar",
            "0412" to "Nav Ringsaker",
            "0415" to "Nav Løten",
            "0417" to "Nav Stange",
            "0419" to "Nav Odal",
            "0420" to "Nav Eidskog",
            "0425" to "Nav Solør",
            "0427" to "Nav Elverum",
            "0428" to "Nav Trysil",
            "0429" to "Nav Åmot",
            "0430" to "Nav Stor-Elvdal",
            "0434" to "Nav Engerdal",
            "0437" to "Nav Nord-Østerdal",
            "0483" to "Nav egne ansatte Innlandet",
            "0491" to "Nav arbeidslivssenter Innlandet",
            "0492" to "Nav rådgivende overleger Innlandet",
            "0496" to "Nav arbeidsrådgivning Innlandet",
            "0501" to "Nav Lillehammer-Gausdal",
            "0502" to "Nav Gjøvik",
            "0511" to "Nav Lesja - Dovre",
            "0513" to "Nav Lom-Skjåk",
            "0515" to "Nav Vågå",
            "0516" to "Nav Midt-Gudbrandsdal",
            "0517" to "Nav Sel",
            "0521" to "Nav Øyer",
            "0528" to "Nav Østre Toten",
            "0529" to "Nav Vestre Toten",
            "0532" to "Nav Jevnaker",
            "0534" to "Nav Hadeland",
            "0538" to "Nav Land",
            "0542" to "Nav Valdres",
            "0587" to "Nav tiltak Innlandet",
            "0600" to "Nav Vest-Viken",
            "0602" to "Nav Drammen",
            "0604" to "Nav Kongsberg",
            "0605" to "Nav Ringerike",
            "0612" to "Nav Hole",
            "0617" to "Nav Hallingdal",
            "0623" to "Nav Midt-Buskerud",
            "0624" to "Nav Øvre Eiker",
            "0626" to "Nav Lier",
            "0632" to "Nav Numedal",
            "0676" to "ROE Regional oppfølgingsenhet Vest-Viken",
            "0683" to "Nav egne ansatte Vest-Viken",
            "0687" to "Nav forvaltningstjenester Vest-Viken",
            "0691" to "Nav arbeidslivssenter Vest-Viken",
            "0692" to "Nav rådgivende overleger Vest-Viken",
            "0696" to "Nav arbeidsrådgivning Vest-Viken",
            "0701" to "Nav Horten",
            "0704" to "Nav Tønsberg",
            "0710" to "Nav Sandefjord",
            "0800" to "Nav Vestfold og Telemark",
            "0805" to "Nav Porsgrunn",
            "0806" to "Nav Skien",
            "0807" to "Nav Notodden og Hjartdal",
            "0811" to "Nav Siljan",
            "0814" to "Nav Bamble",
            "0815" to "Nav Kragerø",
            "0817" to "Nav Drangedal",
            "0821" to "Nav Midt-Telemark",
            "0826" to "Nav Tinn",
            "0833" to "Nav Vest-Telemark",
            "0883" to "Nav egne ansatte Vestfold og Telemark",
            "0891" to "Nav arbeid og helse Vestfold og Telemark",
            "0901" to "Nav Risør",
            "0904" to "Nav Grimstad",
            "0906" to "Nav Arendal",
            "0914" to "Nav Øst i Agder",
            "0926" to "Nav Lillesand",
            "0928" to "Nav Birkenes",
            "0929" to "Nav Åmli",
            "0937" to "Nav Evje og Hornnes",
            "1000" to "Nav Agder",
            "1001" to "Nav Kristiansand",
            "1002" to "Nav Lindesnes",
            "1014" to "Nav Midt-Agder",
            "1034" to "Nav Hægebostad",
            "1037" to "Nav Lister",
            "1083" to "Nav egne ansatte Agder",
            "1087" to "Nav tiltak Agder",
            "1091" to "Nav arbeidslivssenter Agder",
            "1096" to "Nav arbeid og helse Agder",
            "1100" to "Nav Rogaland",
            "1101" to "Nav Dalane",
            "1102" to "Nav Sandnes",
            "1106" to "Nav Haugesund-Utsira",
            "1119" to "Nav Hå",
            "1120" to "Nav Klepp-Time",
            "1122" to "Nav Gjesdal",
            "1124" to "Nav Sola",
            "1127" to "Nav Randaberg-Kvitsøy",
            "1130" to "Nav Strand",
            "1133" to "Nav Hjelmeland",
            "1134" to "Nav Suldal",
            "1135" to "Nav Sauda",
            "1146" to "Nav Tysvær",
            "1149" to "Nav Karmøy-Bokn",
            "1160" to "Nav Vindafjord-Etne",
            "1161" to "Nav Eiganes og Tasta",
            "1162" to "Nav Hundvåg og Storhaug",
            "1164" to "Nav Hillevåg og Hinna",
            "1165" to "Nav Madla",
            "1169" to "Nav Rennesøy og Finnøy",
            "1183" to "Nav egne ansatte Rogaland",
            "1187" to "Nav tiltak Rogaland",
            "1191" to "Nav arbeidslivssenter Rogaland",
            "1193" to "Nav Marked Nord-Rogaland",
            "1194" to "Nav Marked Sør-Rogaland",
            "1195" to "Nav IPS Rogaland",
            "1196" to "Nav arbeidsrådgivning Rogaland",
            "1200" to "Nav Vestland",
            "1202" to "Nav Bergen sør",
            "1203" to "Nav Bergen nord",
            "1206" to "Nav Bergen vest",
            "1208" to "Nav Bergen sentrum",
            "1216" to "Nav Sveio",
            "1219" to "Nav Bømlo",
            "1221" to "Nav Stord",
            "1222" to "Nav Fitjar",
            "1223" to "Nav Tysnes",
            "1224" to "Nav Kvinnherad",
            "1228" to "Nav Ullensvang",
            "1232" to "Nav Eidfjord",
            "1233" to "Nav Ulvik",
            "1235" to "Nav Voss",
            "1238" to "Nav Kvam",
            "1242" to "Nav Samnanger",
            "1243" to "Nav Bjørnafjorden",
            "1244" to "Nav Austevoll",
            "1246" to "Nav Øygarden",
            "1247" to "Nav Askøy",
            "1251" to "Nav Vaksdal",
            "1253" to "Nav Osterøy",
            "1263" to "Nav Alver",
            "1266" to "Nav Fensfjorden",
            "1283" to "Nav egne ansatte Vestland",
            "1287" to "Nav tiltak Vestland",
            "1291" to "Nav arbeidslivssenter Vestland",
            "1296" to "Nav Vestland kompetansesenter for arbeidshelse",
            "1401" to "Nav Kinn",
            "1412" to "Nav Solund",
            "1417" to "Nav Vik",
            "1420" to "Nav Sogndal",
            "1422" to "Nav Aurland og Lærdal",
            "1424" to "Nav Årdal",
            "1426" to "Nav Luster",
            "1428" to "Nav Askvoll",
            "1432" to "Nav Sunnfjord og Ytre Sogn",
            "1443" to "Nav Nordfjord",
            "1476" to "Nav sjukefråværsavdeling region Sunnfjord",
            "1500" to "Nav Møre og Romsdal",
            "1502" to "Nav Molde",
            "1504" to "Nav Ålesund",
            "1505" to "Nav Kristiansund",
            "1517" to "Nav ytre Søre Sunnmøre",
            "1520" to "Nav Ørsta-Volda",
            "1528" to "Nav Sykkylven - Stranda",
            "1531" to "Nav Sula",
            "1532" to "Nav Giske",
            "1535" to "Nav Vestnes",
            "1539" to "Nav Rauma",
            "1547" to "Nav Aukra",
            "1548" to "Nav Hustadvika",
            "1554" to "Nav Averøy",
            "1557" to "Nav Gjemnes",
            "1563" to "Nav Indre Nordmøre",
            "1573" to "Nav Smøla",
            "1576" to "Nav Aure",
            "1580" to "Nav Haram",
            "1583" to "Nav egne ansatte Møre og Romsdal",
            "1591" to "Nav arbeidslivssenter Møre og Romsdal",
            "1612" to "Nav Heim",
            "1620" to "Nav Hitra Frøya",
            "1621" to "Nav Ørland",
            "1630" to "Nav Nord-Fosen",
            "1634" to "Nav Oppdal og Rennebu",
            "1638" to "Nav Orkland",
            "1640" to "Nav Røros, Os og Holtålen",
            "1648" to "Nav Midtre Gauldal",
            "1657" to "Nav Skaun Melhus",
            "1663" to "Nav Malvik",
            "1683" to "Nav egne ansatte Trøndelag",
            "1702" to "Nav Inn-Trøndelag",
            "1703" to "Nav Midtre Namdal",
            "1719" to "Nav Levanger",
            "1721" to "Nav Verdal",
            "1742" to "Nav Indre Namdal",
            "1751" to "Nav Nærøysund",
            "1783" to "Nav Værnes",
            "1800" to "Nav Nordland",
            "1804" to "Nav Bodø",
            "1805" to "Nav Narvik",
            "1813" to "Nav Sør-Helgeland",
            "1820" to "Nav Ytre Helgeland",
            "1824" to "Nav Vefsna",
            "1826" to "Nav Hattfjelldal",
            "1828" to "Nav Nesna",
            "1832" to "Nav Hemnes",
            "1833" to "Nav Rana",
            "1834" to "Nav Lurøy",
            "1837" to "Nav Sør-Salten",
            "1841" to "Nav Indre Salten",
            "1848" to "Nav Steigen",
            "1851" to "Nav Lødingen",
            "1856" to "Nav Røst",
            "1857" to "Nav Værøy",
            "1860" to "Nav Lofoten",
            "1866" to "Nav Hadsel",
            "1867" to "Nav Bø",
            "1868" to "Nav Øksnes",
            "1870" to "Nav Sortland",
            "1871" to "Nav Andøy",
            "1883" to "Nav egne ansatte Nordland",
            "1891" to "Nav arbeidslivssenter Nordland",
            "1893" to "Nav arbeidsrådgiving Nordland",
            "1900" to "Nav Troms og Finnmark",
            "1902" to "Nav Tromsø",
            "1903" to "Nav Sør-Troms",
            "1923" to "Nav Salangen-Lavangen-Dyrøy",
            "1924" to "Nav Målselv-Bardu",
            "1931" to "Nav Senja-Sørreisa",
            "1933" to "Nav Balsfjord-Storfjord",
            "1936" to "Nav Karlsøy",
            "1938" to "Nav Lyngen",
            "1940" to "Nav Gáivuotna/Kåfjord",
            "1941" to "Nav Skjervøy",
            "1942" to "Nav Nordreisa",
            "1983" to "Nav egne ansatte Troms og Finnmark",
            "1987" to "Nav tiltak Troms og Finnmark",
            "1991" to "Nav arbeidslivssenter Troms og Finnmark",
            "2002" to "Nav Vardø",
            "2003" to "Nav Vadsø",
            "2004" to "Nav Hammerfest-Måsøy",
            "2011" to "Nav Ávjovárri",
            "2012" to "Nav Alta-Kvænangen-Loppa",
            "2015" to "Nav Hasvik",
            "2019" to "Nav Nordkapp",
            "2020" to "Nav Porsanger",
            "2022" to "Nav Lebesby",
            "2023" to "Nav Gamvik",
            "2024" to "Nav Berlevåg",
            "2025" to "Nav Deatnu/Tana",
            "2027" to "Nav Unjárga/Nesseby",
            "2028" to "Nav Båtsfjord",
            "2030" to "Nav Sør-Varanger",
            "2096" to "Nav arbeidsrådgivningskontor  Troms og Finnmark",
            "2103" to "Nav Vikafossen",
            "2811" to "Internrevisjonen",
            "2820" to "Avdeling for mennesker og organisasjon",
            "2821" to "Økonomi- og styringsavdelingen",
            "2823" to "Kommunikasjonsavdelingen",
            "2826" to "Kunnskapsavdelingen",
            "2827" to "Juridisk avdeling",
            "2828" to "Oljepionerene",
            "2830" to "Ytelsesavdelingen",
            "2840" to "Arbeidsavdelingen",
            "2841" to "Robotadministrasjon arbeids- og tjenestelinjen",
            "2844" to "Velferdsavdelingen",
            "2846" to "Avdeling for brukeropplevelse",
            "2930" to "IT-avdelingen",
            "2950" to "Nav drift og utvikling - administrative tjenester",
            "2960" to "Nav økonomiteneste",
            "2970" to "IT-avdelingen",
            "2980" to "IT-avdelingen",
            "2990" to "Teknologiavdelingen",
            "4000" to "innsatsteam EU-EØS",
            "4100" to "Nav styringsenhet kontaktsenter",
            "4101" to "Nav kontaktsenter Øst-Viken",
            "4105" to "Nav kontaktsenter Innlandet",
            "4106" to "Nav kontaktsenter Oslo og Vest-Viken",
            "4107" to "Nav kontaktsenter Vestfold og Telemark",
            "4110" to "Nav kontaktsenter Agder",
            "4111" to "Nav kontaktsenter Rogaland",
            "4112" to "Nav kontaktsenter Vestland",
            "4114" to "Nav kontaktsenter Nord-Vestlandet",
            "4116" to "Nav kontaktsenter Trøndelag",
            "4118" to "Nav kontaktsenter Nordland Bodø",
            "4119" to "Nav kontaktsenter Troms og Finnmark",
            "4121" to "Nav kontaktsenter Nordland Mo",
            "4151" to "Nav økonomi stønad",
            "4152" to "Nav innsatsteam økonomi",
            "4153" to "Forskudd dagpenger",
            "4154" to "Nasjonal oppfølgingsenhet",
            "4155" to "Nav kontaktsenter innsyn",
            "4156" to "Nav økonomi stønad - dokumentsenter",
            "4200" to "Klageinstans styringsenhet",
            "4250" to "Klageinstans Kristiansand",
            "4251" to "Klageinstans - bidrag - inn",
            "4252" to "Klageinstans - bidrag - klage",
            "4253" to "Klageinstans - bidrag - tilbakekreving",
            "4254" to "Klageinstans - bidrag - vakt",
            "4255" to "Klageinstans - tiltakspenger - inn",
            "4258" to "Klageinstans - tiltak",
            "4259" to "Klageinstans - sykepenger - inn",
            "4260" to "Klageinstans - arbeidsavklaringspenger - inn",
            "4270" to "Klageinstans - dagpenger - inn",
            "4279" to "Klageinstans sakskostnader",
            "4280" to "Klageinstans - tilleggsstønader - inn",
            "4286" to "Klageinstans - uføretrygd - inn",
            "4287" to "Klageinstans - erstatning",
            "4291" to "Klageinstans Oslo",
            "4292" to "Klageinstans Trondheim",
            "4293" to "Klageinstans Tønsberg",
            "4294" to "Klageinstans Bergen",
            "4295" to "Klageinstans Tromsø",
            "4303" to "Nav id og fordeling",
            "4400" to "Nav arbeid og ytelser styringsenhet",
            "4401" to "Nav arbeid og ytelser Sarpsborg",
            "4402" to "Nav arbeid og ytelser Romerike",
            "4403" to "Nav arbeid og ytelser Kristiania",
            "4405" to "Nav arbeid og ytelser Innlandet",
            "4407" to "Nav arbeid og ytelser Tønsberg",
            "4408" to "Nav arbeid og ytelser Skien",
            "4410" to "Nav arbeid og ytelser Sørlandet",
            "4411" to "Nav arbeid og ytelser Karmøy",
            "4415" to "Nav arbeid og ytelser Møre og Romsdal",
            "4416" to "Nav arbeid og ytelser Trondheim",
            "4418" to "Nav arbeid og ytelser Fauske",
            "4450" to "Nav arbeid og ytelser - dagpenger",
            "4461" to "Nav arbeid og ytelser grunn- og hjelpestønad",
            "4462" to "Nav arbeid og ytelser - tilleggsstønad",
            "4465" to "Nav arbeid og ytelser Trondheim - DP grensearb",
            "4468" to "Nav arbeid og ytelser uføretrygd",
            "4469" to "Nav arbeid og ytelser lønnsgaranti",
            "4470" to "Nav arbeid og ytelser Innlandet - EØS dagpenger",
            "4473" to "Nav AY inntektskompensasjon EØS",
            "4474" to "Nav arbeid og ytelser - sykepenger bosatt utland",
            "4475" to "Nav arbeid og ytelser - uføretrygd bosatt utland",
            "4476" to "Nav arbeid og ytelser - uføretrygd Norge/utland",
            "4477" to "Nav arbeid og ytelser feilsituasjoner",
            "4478" to "Nav innsatsteam lokal",
            "4479" to "Nav innsatsteam klage",
            "4480" to "Nav arbeid og ytelser rådgivende legetjeneste",
            "4481" to "Nav innsatsteam erstatning",
            "4483" to "Nav arbeid og ytelser egne ansatte",
            "4485" to "Nav arbeid og ytelser - hjelpemidler",
            "4486" to "Nav arbeid og ytelser lønnskompensasjon",
            "4487" to "Nav arbeid og ytelser - sykdom i familien",
            "4488" to "Nav arbeid og ytelser - sykepenger",
            "4489" to "Nav AY enslig forsørger",
            "4491" to "Nav arbeid og ytelser arbeidsavklaringspenger",
            "4500" to "Nav kontroll styringsenhet",
            "4503" to "Nav kontroll Øst",
            "4511" to "Nav kontroll Vest",
            "4519" to "Nav kontroll Nord",
            "4530" to "Nav medlemskap og avgift",
            "4534" to "Nav registerforvaltning",
            "4550" to "Nav kontroll analyse Oslo",
            "4700" to "Styringsenheten for Nav hjelpemidler og tilrettelegging",
            "4701" to "Nav hjelpemiddelsentral Øst-Viken",
            "4702" to "Nav hjelpemiddelsentral Akershus",
            "4703" to "Nav hjelpemiddelsentral Oslo",
            "4704" to "Nav hjelpemiddelsentral Innlandet-Elverum",
            "4705" to "Nav hjelpemiddelsentral Innlandet-Gjøvik",
            "4706" to "Nav hjelpemiddelsentral Vest-Viken",
            "4707" to "Nav hjelpemiddelsentral Vestfold og Telemark",
            "4710" to "Nav hjelpemiddelsentral Agder",
            "4711" to "Nav hjelpemiddelsentral Rogaland",
            "4712" to "Nav hjelpemiddelsentral Vestland-Bergen",
            "4714" to "Nav hjelpemiddelsentral Vestland-Førde",
            "4715" to "Nav hjelpemiddelsentral Møre og Romsdal",
            "4716" to "Nav hjelpemiddelsentral Trøndelag",
            "4718" to "Nav hjelpemiddelsentral Nordland",
            "4719" to "Nav hjelpemiddelsentral Troms og Finnmark",
            "4781" to "Nav sentral forsyningsenhet",
            "4800" to "Nav familie- og pensjonsytelser styringsenhet",
            "4803" to "Nav familie- og pensjonsytelser Oslo 2",
            "4806" to "Nav familie- og pensjonsytelser Drammen",
            "4808" to "Nav familie- og pensjonsytelser Porsgrunn",
            "4812" to "Nav familie- og pensjonsytelser Bergen",
            "4815" to "Nav familie- og pensjonsytelser Ålesund",
            "4817" to "Nav familie- og pensjonsytelser Steinkjer",
            "4819" to "Nav økonomi pensjon",
            "4820" to "Nav familie- og pensjonsytelser Vadsø",
            "4833" to "Nav familie- og pensjonsytelser Oslo 1",
            "4842" to "Nav familie- og pensjonsytelser Stord",
            "4849" to "Nav familie- og pensjonsytelser Tromsø",
            "4860" to "Nav familie- og pensjonsytelser Farskap",
            "4862" to "Nav familie- og pensjonsytelser utland Ålesund",
            "4863" to "Nav familie- og pensjonsytelser midlertidig enhet",
            "4864" to "Nav familie- og pensjonsytelser feilsituasjoner",
            "4865" to "Nav familie- og pensjonsytelser bidrag utland",
            "4867" to "Nav familie- og pensjonsytelser foreldrepenger",
            "4883" to "Nav familie- og pensjonsytelser egne ansatte",
            "5301" to "Nav Holmestrand",
            "5302" to "Nav Færder",
            "5303" to "Nav Larvik",
            "5700" to "Nav Trøndelag",
            "5701" to "Nav Falkenborg",
            "5702" to "Nav Lerkendal",
            "5703" to "Nav Indre Fosen",
            "5772" to "Nav arbeidslivssenter Trøndelag",
            "5773" to "Nav Rådgivningstjeneste Trøndelag",
            "9401" to "Nav innkreving",
            "9504" to "RIKSREVISJONEN",
        )
    }
}
